version: '3.0'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  postgresql-server:
    hostname: postgresql-server
    container_name: postgresql-server
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=pizza_user
      - POSTGRES_DB=pizza_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  mongodb:
    hostname: mongodb-server
    container_name: mongodb-server
    image: mongo:4.4.17
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
      - MONGO_INITDB_DATABASE=stock_db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '8085:8085'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb-server



networks:
  default:
    driver: bridge

volumes:
  postgresql_data: